ministryofjustice/cla-end-to-end-tests

features/means_test.feature, features/steps/finance_form_helpers.py, features/steps/means_test.py, helper/helper_base.py
- Created a helper file (`finance_form_helpers.py`) for filling in the input fields in the finance --> finance form
- Added steps for means test
- Filled in details form under **Finances outer tab**
- Filled finance form under **Finances outer tab**
- Saved the form by clicking the `save assessment button`
- Confirmed means test was successful by checking for the following message: 
> The means test has been saved. The current result is eligible for Legal Aid
=> LGA-1843 Means test pass universal credit

README.md, run_test_local_chrome_driver.sh
Add wrapper script for running tests using local chrome driver
Update README to reflect how tests are run using local chrome driver
=> Add wrapper script for running tests using local chrome driver

features/assign_complete_case.feature, features/steps/assign_complete_case.py, features/steps/assign_incomplete_case.py, features/steps/create_eligible_finances.py, helper/helper_base.py
- Add tests for assigning complete case to specialist provider
- Add an explicit wait step for the end of the finance tab step to complete
=> LGA-1845 Assign complete case

behave/features/cla_eligible_callback.feature, behave/features/constants.py, behave/features/steps/cla_eligible_callback.py, behave/features/steps/cla_eligible_confirmation.py, behave/helper/backend.py, behave/helper/helper_base.py, behave/run_test_local_chrome_driver.sh
Added in steps for callback scenario. 
Uses several of the steps from cla_eligible_confirmation feature
=> LGA-1822 Confirmation-page-with-call-back-reference-number

orb.yml
Have updated orb.yml so that it adds the new fixture to the test db.
=> LGA-1847 - select case from dashboard - further update 

behave/docker-compose.yml, behave/features/constants.py, behave/features/environment.py, behave/features/specialist_provider.feature, behave/features/steps/specialist_provider.py, behave/helper/helper_base.py, behave/requirements.txt, behave/setup.cfg
This pull request is for the following: 
- added step to move to the finances tab and make sure thats its completed and displayed
- initial screenshot on test failure functionality
=> LGA 1849 View case finance details

behave/docker-compose.yml, behave/features/cla_pick_up_digital_case_by_call_back.feature, behave/features/constants.py, behave/features/steps/cla_pick_up_digital_case_by_call_back.py, behave/helper/backend.py, behave/helper/helper_base.py, behave/requirements.txt, behave/run_test_local.sh
This needs the creation of the fixture containing the cases so can use those references to create the callbacks to be merged first.
Requires updated version of cla_common that can be used with python3. Issue with version of black when looking at pre-commits with that change.
=> LGA 1825 p4 child 1 calendar view callback slots

behave/features/alternative_help.feature, behave/features/steps/alternative_help.py, behave/features/steps/assign_incomplete_case.py, behave/features/steps/common_steps.py, behave/features/steps/diagnosis_discrimination_steps.py
Create an out of scope diagnosis for alternative help case
=> LGA-1828 - Create an out of scope diagnosis for alternative help case

behave/features/cla_contact_us.feature, behave/features/cla_eligible.feature, behave/features/constants.py, behave/features/diagnosis.feature, behave/features/steps/cla_contact_us.py, behave/features/steps/cla_eligible_callback_or_confirmation.py, behave/features/steps/diagnosis.py
1) New step to for full name input field
2) Resolved missing step
3) Updating pre-existing steps and correcting wording in steps
4) Adding in journey number and ticket number
=> LGA-2106-Contact-Civil-Legal-Advice

behave/features/steps/assign_complete_case.py, behave/features/steps/means_test.py
Amended the finance tab slightly with code and took away an unneeded assert.
=> Reduce test failure rate.

behave/docker-compose.yml
Load backend test users and credentials
Required for https://github.com/ministryofjustice/cla_backend/pull/816
=> LGA-2187 - Load backend test users and credentials

behave/features/alternative_help.feature, behave/features/assign_case.feature, behave/features/assign_face_to_face.feature, behave/features/cla_pick_up_digital_case_by_call_back.feature, behave/features/cla_select_digital_case_by_call_back.feature, behave/features/constants.py, behave/features/create_case_and_user.feature, behave/features/diagnosis.feature, behave/features/foxadmin.feature, behave/features/means_test.feature, behave/features/search_for_user_create_new_case.feature, behave/features/specialist_provider.feature, behave/features/steps/alternative_help.py, behave/features/steps/common_steps.py, behave/features/steps/foxadmin.py, behave/features/steps/specialist_provider.py, behave/features/steps/test_steps.py, behave/setup.cfg
Created new feature file for fox admin journeys.
Refactored login so always use the same step no matter who logged in as.
Shifted the constants for usernames and passwords to constants.py
=> LGA-1860 Fox admin login

behave/features/constants.py, behave/features/foxadmin.feature, behave/features/foxadmin_assign_staff.feature, behave/features/steps/foxadmin_assign_staff.py
Added in steps to select a user and change their status for P11 user journey
=> LGA 1863 Assign staff status to a user

.circleci/config.yml, .flake8, .pre-commit-config.yaml, behave/README.md, behave/features/constants.py, behave/features/environment.py, behave/features/steps/alternative_help.py, behave/features/steps/assign_case.py, behave/features/steps/assign_face_to_face.py, behave/features/steps/cla_contact_us.py, behave/features/steps/cla_eligible_callback_or_confirmation.py, behave/features/steps/cla_in_scope.py, behave/features/steps/cla_pick_up_digital_case_by_call_back.py, behave/features/steps/cla_select_digital_case_by_call_back.py, behave/features/steps/common_steps.py, behave/features/steps/diagnosis.py, behave/features/steps/foxadmin.py, behave/features/steps/means_test.py, behave/features/steps/regex_steps.py, behave/features/steps/search_for_user_create_new_case.py, behave/features/steps/smoke_test_steps.py, behave/features/steps/specialist_provider.py, behave/features/steps/test_steps.py, behave/helper/backend.py, behave/helper/helper_base.py, behave/helper/helper_web.py, behave/requirements.txt
Adding pre-commit which contains flake8 and black configs
=> Feature/lga 2182 add pre-commit

behave/docker-compose.yml
=> LGA-2331: Allow socket server image to be specified

behave/helper/helper_base.py
End to end tests were not running as calculation of helperfunc property date_start_this_month was coming up with a negative number for months.
Updated so works for January and also checked 29th Feb as well.
=> LGA-2364 Update calculation of start_date so that it works for January.

behave/features/cla_fala/fala_end_to_end_tests.feature, behave/features/steps/fala_end_to_end_tests.py
This PR adds an end-to-end test for FALA. 
It covers the "Search by organisation" scenario:
**Given** I am on the Find a legal aid adviser homepage
**And** I provide location details 
**And** I provide an organisation name 
**When** I select the Search button
**Then** I am taken to the search results page
**And** one result is visible on the results page
=> LGA-2386 FALA end-to-end test for search by organisation name

behave/features/cla_fala/fala_end_to_end_tests.feature, behave/features/steps/fala_end_to_end_tests.py
- Add accessibility hooks to FALA tests.
- Refactor the test and feature files.
Check if the accessibility are all passing?
=> LGA-2351: ♿️ Enable accessibility e2e tests for FALA

behave/features/steps/common_steps.py
Reverts ministryofjustice/cla-end-to-end-tests#113
=> Revert "Feature/lga 2403 e2e axe waits"

behave/.env.m1.example, behave/README.md, behave/docker-compose.local.yml, behave/docker-compose.yml
Adds the env variables to build clapublic, requires the clapublic and backend fixes to be merged
=> M1 e2e fixes

behave/features/cla_frontend/frontend_income.feature, behave/features/steps/frontend_income.py
Adds in tests for the 25,000 limit removal on cla_frontend
=> Lga 2752 cost limit e2 e tests

behave/docker-compose.yml
=> Disable security to run tests

behave/docker-compose.yml
=> Add in nohttp

behave/features/cla_public/public_eligible.feature
New uneligible page for hlpas categories.
Related to https://github.com/ministryofjustice/cla_public/pull/1256
=> LGA-3027 - New uneligible page for hlpas categories

behave/features/steps/frontend_assignment.py
Fix the flaky E2E Tests by adding a scroll step that means that the diversity tab can be clicked.
=> Fix End to End Frontend Assignments

behave/features/steps/common_steps.py
Adds logic to stale element exceptions to allow test to handle this error approrpriately
=> Repair failing pipeline
