README.md
docker-compose.yml
features/constants.py
features/environment.py
features/steps/test_steps.py
helper/helper_web.py

Add steps for running tests using local chrome driver
Update docker-compose.yaml to pass application and selenium urls to end-to-end tests through environment variables
Add constants for applications and selenium urls that are read from environment variables
Update tests and setup scripts to read applications and selenium urls from constants file

Add steps for running tests using local chrome driver

---

behave/docker-compose.yml

The non-empty string value it was is not a valid value for its usage by
the Sentry SDK, so it's not a good default
Changing it to the empty string will allow `cla_public` to parse the default value, specifically allowing the suite to run when `SENTRY_DSN` is not set on CircleCI for the pipeline that's running, which it doesn't at the moment.
Other changes: the `SENTRY_DSN` has now been removed from this project's project settings on CircleCI, so its passing tests aren't relying on the old behaviour.

LGA-1970 - Set SENTRY_DSN to empty string if absent

---

.gitignore
behave/features/alternative_help.feature
behave/features/constants.py
behave/features/create_case_and_user.feature
behave/features/steps/alternative_help.py
behave/features/steps/test_steps.py

- Make the `And enter the client's personal details` step reusable by getting the form details from the context
- Save the case reference when a new case is created in the `When I select to 'Create a case'`
- Create user and case for assigning alternative help

LGA-1827 alternative help create user and case

---

behave/README.md
behave/docker-compose.local.yml
behave/docker-compose.m1.yml
behave/run_test_local_m1.sh

Currently users that are using an Apple M1 computer can not execute tests. This is an update with new docker yml files and shell scripts to get arounds unsupported arm64 packages and images.

Work arounds for M1 arm64 Apple processor problems

---

behave/features/alternative_help.feature
behave/features/constants.py
behave/features/diagnosis_debt_court_proceedings.feature
behave/features/diagnosis_discrimination.feature
behave/features/steps/alternative_help.py
behave/features/steps/assign_incomplete_case.py
behave/features/steps/cla_select_digital_case_by_call_back.py
behave/features/steps/common_steps.py
behave/features/steps/search_for_user_create_new_case.py
behave/features/steps/specialist_provider.py
behave/features/steps/test_steps.py
behave/helper/helper_base.py

Further steps for user journey p6 and refactoring
Created common functionality to deal with clicking buttons - allows for stale element exception.
Removed unused import statements and updates assert_header_on_page function to allow for more than one h1 element.
Changed I am taken to the "{type_of_user}" case details page as I think it was using the wrong step at the end.
Refactored "inscope" and "outofscope" methods so use same step.
Updated the steps at start of the @in_scope_debt_court to match other scenarios.

LGA 1829 out of scope diagnosis assign alternative help succeeds

---

behave/features/alternative_help.feature
behave/features/constants.py
behave/features/diagnosis.feature
behave/features/steps/alternative_help.py

Added in extra step for when alternative help cannot be assigned.
Tech debt:
Updated the steps to see user details.
Changed the description of diagnosis.feature to be more generic as it now has two scenarios.

LGA-2136 Alternative help fails

---

behave/docker-compose.yml

Added a new config value in docker-compose.yml with STATIC_FILE_BACKEND to allow static files to built and used in docker builds.

Adding static file value in docker-compose clabackend values

---

behave/features/environment.py
behave/features/steps/assign_case.py
behave/features/steps/means_test.py

- Wait for specialist providers to load before clicking the assign provider button - Specialist providers are only loaded after clicking on the assign tab on new cases, so I have added a polling wait to avoid a race condition of clicking the assign button before the providers have loaded.
- According to the TAP team the issue of the click being intercepted for the inner finances tab was caused by case bar being always fixed at the top of the page. On smaller viewports(resizing the browser) this causes the finances tab disappear behind the case bar which causes it to receive the clicks intended for the inner finances tab.
To remedy this issue, the TAP team have suggested that we set the window size to a fixed size. I have added a call to maximise the page before the start of all the tests …

Wait for tabs to be clickable

---

behave/features/environment.py

Added a before_feature hook which patches the scenarios in each feature with an autoretry.
This will at a maximum retry 3 times.
This is to deal with the flakey test issue that we have mostly occuring on circleci, generally around how long something takes to load.

LGA 2283 Retry test failures

---

behave/features/cla_fala/fala_end_to_end_tests.feature
behave/features/steps/fala_end_to_end_tests.py

This is an end to end test to verify that FALA is working accordingly. It checks if:
1. the user is on the homepage
2. the input field for postcode/city is filled with the user's text
3. the search button send the request
4. the result page appears and displays the search result
5. a filter can be selected
6. the filter can be applied
7. the filter create a new request with the latest information

Feature/LGA-2382: Apply filter on search

---

behave/features/cla_fala/fala_end_to_end_tests.feature
behave/features/steps/fala_end_to_end_tests.py

This PR adds an end-to-end test for FALA. 
It covers the "I search for a town that does not have an solicitors and fails" scenario:
**Given** I am on the Find a legal aid adviser homepage
**And** I provide location details via “Falmouth“ 
**Then** the page shows an error message

Feature/LGA-2391: FALA e2e tests - search with no results

---

behave/features/cla_fala/fala_end_to_end_tests.feature
behave/features/steps/fala_end_to_end_tests.py

- Covers the applying filters on the homepage search, filters correctly scenario:
**Given** I collect the resulting number for a generic search
**And** I provide location details via “postcode“
**And** I filter by the category “Crime“
**When** I select the Search button
**Then** I am taken to the search results page
**Then** my result number has been updated to reflect the applied filter.
- Refactored the three functions used for search results page (placed common logic into assert_result_page function)
- Added an additional step to a previous test to check that results are shown when applying a filter (discussed with Patrick)

LGA-2389 add filtering on homepage test and refactor test steps

---

orb.yml

Copy artifacts to /tmp as behave directory is not available to projects that use this orb
- [] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

Copy artifacts to /tmp

---

behave/features/environment.py
behave/features/steps/fala_end_to_end_tests.py
behave/helper/helper_base.py

The FALA end-to-end test (@fala-apply-filter-on-homepage) that run right after the change language tests (@fala-dom-translation) were failing only on cla_public. The error was that the page was translated to Scot Gaelic in the first test and did not revert to English in the next test.
Further investigation found that the time.sleep() function in our check_accessibility function was causing this only in our cla_public pipeline.
This work:
- adds a delete_cookies helper function
- uses the delete_cookies function after each test scenario
- updates some of the error logging message so we can see what the actual values are if the test fails again in future
Tried running all tests where we log out at the end (but commented out the log out step) in one run and these tests still passed. 
I …

LGA-2414/fix CLA FALA end-to-end test failing on cla_public

---

behave/features/cla_backend/backend_reports.feature
behave/features/cla_backend/backend_users.feature
behave/features/cla_fala/fala_end_to_end_tests.feature
behave/features/cla_frontend/frontend_assignments.feature
behave/features/cla_frontend/frontend_create_case_and_user.feature
behave/features/cla_frontend/frontend_existing_callback.feature
behave/features/cla_frontend/frontend_means_test.feature
behave/features/cla_frontend/frontend_specialist_provider.feature
behave/features/cla_public/public_contact_us.feature
behave/features/cla_public/public_eligible.feature
behave/features/steps/fala_end_to_end_tests.py
behave/helper/constants.py

FALA no longer allows searching by city. This PR updates our end to end tests to reflect this.
- Most tests that had used "London" have been replaced with a postcode. 
- A test has been added to check that an error is returned when a user searches by city or when an invalid postcode is used
- The search no results test scenario has been edited to check when searching for an organisation that does not exist. This is because when a user searches for any valid postcode, it will always return the nearest available organisation 
Added tags on the top of each .feature file to allow us to call specific tests in our repository pipelines

LGA-2448 update end-to-end tests to reflect searching by only postcode

---

behave/features/cla_frontend/frontend_means_test.feature
behave/features/cla_public/public_contact_us.feature
behave/features/steps/frontend_means_test.py
behave/features/steps/public_contact_us.py

Fixes 2 failing tests:
1. Makes the **call someone else instead of me** test scenario pass when run out of hours (after 5:30pm). This test would fail after 5:30pm as the 'Call Today' option would disappear. If the 'Not Today' option is not visible, then it will select the next available option (call another day).
-  public_contact_us.feature
- public_contact_us.py
2. "**Successful means test assessment resulting in user being eligible for legal aid**" - this has been failing in the pipeline regularly on the `And I move onto Finances inner-tab` step. Screenshots on failure show that the tab was not visible, I have forced it to scroll to the top in this scenario. 
- frontend_means_test.py
Proof that the first test passes out of hours in [this …

LGA-2303 update test to pass out of hours

---

behave/features/cla_frontend/frontend_means_test.feature
behave/features/cla_frontend/frontend_specialist_provider.feature
behave/features/steps/frontend_specialist_provider.py

Newly created fixture case must be being used for the legal help form scenario as the test fails as it returns £300.00 for one of the items.
Required.

LGA-2602 Scenario to edit case by operator and specialist provider

---

.circleci/config.yml
.circleci/define_build_environment_variables
.circleci/pull_images
orb.yml

- Removed the building of the end-to-end image
- Updated behave job to pull images using OIDC 
- Updated Orb to pull images using OIDC 
Previously the resulting image was being used by the `ministryofjustice/cla-end-to-end-tests` orb. It was being used as the base image for the environment that the end-to-end tests ran on. This meant that in which ever pipeline the orb was used in, it always had access to the end-to-end files.
The new OIDC method(how cloud-platform set it up) doesn't allow us to use docker executor with an image from our private ecr repository. So instead we use a machine executor and checkout the end-to-end code when the orb is running.
The `ministryofjustice/cla-end-to-end-tests` orb needs to pull images from multiple ecr repos. Previously it just needed to authenticate …

LGA-2642 adding irsa circleci access

---

behave/features/steps/frontend_assignment.py

- Changes how the scope integration test works.
- Before: Waits for element "decision-form" to be loaded, this is a parent element to a number of text fields.
- After: Loads in the multiple child elements by their class name. This should allow us to wait until they are all loaded before we assert what their text contains.

LGA 2705: Fix scope decision integration test failing too often

---

behave/features/steps/frontend_assignment.py

Fixes the flaky scope decision test by referencing the relative xpath of the element rather than by class name.
This has been ran 5 times on the Pipeline with all tests successful, thus hopefully fix the flaky test.

LGA 2723 - Fixed flaky scope decision test

---

behave/features/steps/frontend_specialist_provider.py

Fixes the flaky end-to-end test which failed due to not explicit timeouts on the CSV Upload page.

LGA 2724: Fix flaky frontend_specialist_provider end-to-end tests

---

behave/features/steps/frontend_assignment.py

Cleans up the print statements, from the previous PR  [https://github.com/ministryofjustice/cla-end-to-end-tests/pull/124](https://github.com/ministryofjustice/cla-end-to-end-tests/pull/124), adding error messages to the assert statements to provide additional debugging context if the assertions fail.

LGA-2705 fix scope decision test failing too often

---

behave/features/cla_frontend/frontend_immigration_asylum.feature
behave/features/steps/common_steps.py
behave/features/steps/frontend_assignment.py

- Adds end-to-end tests for the work done in [LGA 2775](https://github.com/ministryofjustice/cla_backend/pull/1013).
- These test both new flows and assert that the added help text works as expected.
Adds a new helper function named `get_node_from_option_name` which takes in a name string and returns the angular node ID for the option. This is a common requirement when writing scope end-to-end tests.

LGA 2775 Immigration and Asylum Scope

---

behave/features/steps/fala_end_to_end_tests.py
behave/helper/helper_base.py

When CSS is applied to a test environment, the naive tests no longer pass as govuk checkboxes are not visible (they are overlaid with other items to make the content more visually appealing). This  change fixes the behave tests to click on the label rather than the checkbox, as that is visible
This was found by enabling CSS in FALA behave tests

click on label for checkboxes rather than on the checkbox itself
